version: '3.8'
services:
  postgres-primary:
    image: postgres:16
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pg-primary-data:/var/lib/postgresql/data
    command: ["postgres", "-c", "wal_level=replica", "-c", "max_wal_senders=10", "-c", "hot_standby=on"]

  postgres-replica:
    image: postgres:16
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5434:5432"
    depends_on:
      - postgres-primary
    volumes:
      - pg-replica-data:/var/lib/postgresql/data
    command: ["postgres", "-c", "hot_standby=on"]

volumes:
  pg-primary-data:
  pg-replica-data: 